import type { Metadata } from "next";
import localFont from "next/font/local";
import { Providers } from "./providers";
import Navbar from "@/components/navbar";
import "./globals.css";
import { auth } from "@/lib/auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col bg-background`}
      >
        <Providers>
          <Navbar session={session} />
          <main className="flex-1">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
